### ISSUE TITLE
Is it possible to autoconnect power?

### ISSUE THREAD

**Issue by taminomara** [Epp-s-Satisfactory-Mods/AutoLink#10]
Hi! I'm building a set of tileable blueprints where each blueprint is a building with splitters/mergers attached to make a manifold. So far, everything connects perfectly, but I haven't figured out if it's possible to autoconnect power lines. If not, I guess it's a feature request then :)

**Comment by zORg-alex** [comment]
It's not even a thing? And here I am struggling to align power nodes to merge, but they refuse to do so.
![image](https://github.com/user-attachments/assets/c3d867b9-37bb-48a7-8882-291837fea7dd)

**Comment by Epp-code** [comment]
Sorry, AutoLink doesn't do power lines, for a few reasons:

1) Power lines cannot hang in the air waiting for a connection, like the other types of connections do.  So AutoLink would have to construct connecting power lines for you, which is not only a core gameplay change, but actually quite a bit more technically complicated than what the mod currently does.

2) It's not clear what all the expected behaviors would be for auto-building power lines.  There are many scenarios where what the user would want is unclear and such a mod would likely do the "wrong" thing a lot, which would mean disassembling lots of things and would be worse (IMO) than just needing to build a single connecting power line yourself.

I, personally, don't have much interest in solving for power lines, as I really just wanted normal construction to work intuitively.  If you're building a tileable blueprint, you should be able to design it so that only one power line needs to be built per section.  Also, railroads can transfer power and there may be some clever solution there (I haven't played with it).  And if somebody makes a wireless power pole mod, AutoLink won't interfere.

If somebody is really desperate or inspired, the complete mod source code is fully available if anybody does want to get a sense of how to tackle power lines but, as I said, actually building power lines is gonna be quite a bit different behind-the-scenes.

**Comment by zORg-alex** [comment]
Oh, I hoped it would be add simple as removing one of two power poles that overlap and reconnect with those that were connected previously if there are connections. Also it could simply connect both overlapped poles. That would be dirtier but absolutely functional. Think about it.
