### ISSUE TITLE
Power line connection

### ISSUE THREAD

**Issue by brummelte** [Epp-s-Satisfactory-Mods/AutoLink#3]
Appreciate the mod. I have a question regarding the automatic connection of power lines. The documentation doesn't fully explain this aspect. Currently, I'm placing a power pole where the next one would be in the blueprint, but it seems like I'm creating two power poles in the same spot. While this mostly works, it's not always consistent. Could you clarify if this is the intended method for linking power lines? Thanks.

**Comment by Epp-code** [comment]
The mod doesn't link power lines - it just does belts, pipes, hypertubes, and railroads, which is why those are called out in the mod description.  Power had crossed my mind but it would represent a change in basic gameplay that I'm trying to avoid.  The philosophy of the mod isn't to alter the core gameplay - it's that you should always be able to tell what is linked by looking at it; that is, if things were built in the right place (as if you had done each one manually) they should end up linked regardless of whether you did it manually or with a blueprint or what order you did it all in.

Power lines are different that the others because wire cannot be constructed in a disconnected state - it can never float in space (AFAIK) waiting for a power pole.

**Comment by brummelte** [comment]
Thanks for clarifying; that explains why it seemed inconsistent in my testing — it never actually worked, and I must have fixed it manually every time I tested.

I understand your point about maintaining core gameplay. One potential solution could be what I mentioned: if two power poles are placed in the same spot, the mod could automatically remove one of the redundant power poles and link it up. The power lines already look continuous even without any action from the mod, but they just aren't truly connected.  

The problem with this approach is that it requires nudging blueprints partially onto the previous ones, but it would still be faster than connecting all the power lines manually afterward.

I understand why power lines are different from handling belts, pipes, and other elements. Appreciate the explanation.

I understand if you decide to close this ticket. I can't see any other solutions besides the one I provided.
